[package]
name = "csvlm"
version = "0.1.2"
authors = ["Lukas Andreas Muller <lamuller@protonmail.com>"]
description = "Language management through CSV tables"
license = "MIT"
repository = "https://github.com/luki/language-parser-csv"

[dependencies]
